# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define "ubuntu" do |app|
    app.vm.box = "bento/ubuntu-16.04"
    app.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
    app.vm.provision "shell",
      inline: "which python2.7 || (sudo apt-get update && sudo apt-get install -y python2.7)"
    app.vm.provision "ansible" do |ansible|
      ansible.playbook = "./playbooks/vagrant.yml"
      ansible.host_vars = {
        "ubuntu" => {"ansible_python_interpreter" => "/usr/bin/python2.7"}
      }
    end
  end
  config.vm.define "centos" do |app|
    app.vm.box = "bento/centos-7.3"
    app.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
    app.vm.provision "ansible" do |ansible|
      ansible.playbook = "./playbooks/vagrant.yml"
    end
  end
end
